console.log("================CALCULATOR==============")
var a=parseInt(process.argv[2])
var b=process.argv[3]
var c=parseInt(process.argv[4])
if(b=='+')
console.log("Adition result: "+(a+c))
if(b=='-')
console.log("Subtraction result: "+(a-c))
if(b=='*')
console.log("Multiplication result: "+(a*c))
if(b=='/')
console.log("Divison result: "+(a/c))
console.log("Argument 0 is:"+process.argv[0])
console.log("Argument 1 is:"+process.argv[1])